name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-lab1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build and test
      working-directory: ./Lab1
      run: make
