name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-lab1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build and test
      run: |
        cd Lab1
        make 
        
  valgrind:

    runs-on: ubuntu-latest
    
    needs: build-lab1
    
    steps:
    - uses: actions/checkout@v2
    - name: check memory
      run: |
        sudo apt install -y valgrind
        valgrind ./bin/program/main
        100







