name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          cd Lab7
          g++ -std=c++11 -ftest-coverage -fprofile-arcs -O0 -o test tests.cpp employer.cpp applicant.cpp database_helper.cpp
          ./test
          gcov -abcfu applicant.cpp employer.cpp database_helper.cpp
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: |
              ./Lab7/employer.cpp.gcov
              ./Lab7/applicant.cpp.gcov
              ./Lab7/database_helper.cpp.gcov
            
