name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          cd Lab7
          gcc -ftest-coverage -fprofile-arcs -O0 -o test test.cpp employer.cpp applicant.cpp
          ./test
          gcov -abcfu lib.c
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./lib.c.gcov
